#!/bin/bash
set -u  # treat unset variables as an error

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

#=================================================
# REMOVE GITLAB RUNNER
#=================================================

# Stop the runner
command -v gitlab-runner >/dev/null 2>&1 && gitlab-runner uninstall

# Uninstall the package previously installed with `ynh_install_app_dependencies`
DEBIAN_FRONTEND=noninteractive apt-get remove -y -qq gitlab-runner

#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

if sudo yunohost service status | grep -q "gitlab-runner"; then
  sudo yunohost service remove "gitlab-runner"
fi
